# Generated by Django 4.2.7 on 2024-01-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0002_account_delete_accounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
