# Generated by Django 4.2.8 on 2024-01-12 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_delete_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('bill_date', models.DateField()),
                ('month_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_bill', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banking.account')),
            ],
        ),
    ]
