# Generated by Django 4.2.7 on 2024-01-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_alter_creditcard_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='bill_date',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_name',
            field=models.CharField(max_length=100),
        ),
    ]
