# Generated by Django 4.2.7 on 2024-01-23 13:35

import banking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_alter_creditcard_bill_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(default=banking.models.generate_number_id, max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='card_number',
            field=models.CharField(default=banking.models.generate_number_id, max_length=8, unique=True),
        ),
    ]
