# Generated by Django 4.2.7 on 2024-03-06 13:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_alter_account_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_detail', to='banking.account', to_field='account_id')),
            ],
        ),
    ]
